\i /docker-entrypoint-migrations/003_finance_campaign_ledger.sql
\i /docker-entrypoint-migrations/004_resident_access.sql
\i /docker-entrypoint-migrations/005_resident_contact_login.sql
\i /docker-entrypoint-migrations/006_notification_channels.sql
\i /docker-entrypoint-migrations/007_resident_password_resets.sql
\i /docker-entrypoint-migrations/008_resident_sessions.sql
\i /docker-entrypoint-migrations/009_stripe_events.sql
\i /docker-entrypoint-migrations/010_stripe_connected_accounts.sql
\i /docker-entrypoint-migrations/011_access_qr_replay_protection.sql
\i /docker-entrypoint-migrations/012_manual_access_audit.sql
\i /docker-entrypoint-migrations/013_guard_operations.sql
\i /docker-entrypoint-migrations/014_tenant_feature_tables.sql
\i /docker-entrypoint-migrations/015_admin_mfa.sql
\i /docker-entrypoint-migrations/016_guard_services.sql
\i /docker-entrypoint-migrations/017_crm_alerts.sql
\i /docker-entrypoint-migrations/018_guard_consigns_and_panic.sql
\i /docker-entrypoint-migrations/019_tenant_guard_schema_completion.sql
\i /docker-entrypoint-migrations/020_tenant_finance_schema_completion.sql
\i /docker-entrypoint-migrations/021_resident_app_refresh_sessions.sql