import { PublicPlanCatalogItem } from '../../types';

export const STATIC_PLAN_CATALOG: PublicPlanCatalogItem[] = [
  {
    code: 'BASIC',
    name: 'Dommia Básico',
    description: 'La solución ágil para organizar cobranza, directorio y comunicación comunitaria sin complicaciones en cotos y privadas pequeñas.',
    monthlyPrice: 1490,
    minProperties: 15,
    maxProperties: 50,
    includesCustomDomain: false,
    customDomainAddonPrice: 490,
    standardDomainPattern: 'standar.dommia.com.mx/{slug}',
    isHighlighted: false,
    sortOrder: 1,
  },
  {
    code: 'STANDARD',
    name: 'Dommia Estándar',
    description: 'Control integral de visitantes con códigos QR dinámicos y conciliación automática de pagos. El plan más elegido por fraccionamientos medianos.',
    monthlyPrice: 2990,
    minProperties: 51,
    maxProperties: 100,
    includesCustomDomain: false,
    customDomainAddonPrice: 490,
    standardDomainPattern: 'standar.dommia.com.mx/{slug}',
    isHighlighted: true,
    sortOrder: 2,
  },
  {
    code: 'PROFESSIONAL',
    name: 'Dommia Profesional',
    description: 'Automatización vehicular total por RFID UHF (< 0.3s), pasarela fintech Stripe/SPEI y bloqueo automático de pluma a morosos.',
    monthlyPrice: 4990,
    minProperties: 101,
    maxProperties: 250,
    includesCustomDomain: true,
    customDomainAddonPrice: 450,
    standardDomainPattern: 'standar.dommia.com.mx/{slug}',
    isHighlighted: false,
    sortOrder: 3,
  },
  {
    code: 'ENTERPRISE',
    name: 'Dommia Enterprise',
    description: 'Arquitectura distribuida para macro-desarrollos de 300+ viviendas, múltiples casetas en clúster, SQLite Edge local, SLA 99.9% y subdominio propio gratis.',
    monthlyPrice: 8990,
    minProperties: 251,
    maxProperties: 800,
    includesCustomDomain: true,
    customDomainAddonPrice: 0,
    standardDomainPattern: '{slug}.dommia.com.mx',
    isHighlighted: false,
    sortOrder: 4,
  },
];